### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by 06Games**
I found MineOS very interresing and I was a little disappointed that a project like this, can have as little language available, so I translate it, and it's done,
thanks in advance for including my tranduction at MineOS

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
Nice! Will create language dependencies for applications in the next couple of hours. Thank you <3

**Comment by 06Games** [comment]
I will thank you for crediting me somewhere
And I really enjoy your reactivity

**Comment by IgorTimofeev** [comment]
Hope this will be enough:

**Comment by 06Games** [comment]
yes, of course, thank you again, and congratulations for all this work

**Pull request merged**
